Portage-2.0.51-r9 RO Lockfile fix, BSD/PPC updates for stat(), primaryuri/mirror restrictions. Webrsync touchups, and doins handling/reporting/fixes for ${D}.

diff --git a/bin/emerge-webrsync b/bin/emerge-webrsync
--- a/bin/emerge-webrsync
+++ b/bin/emerge-webrsync
@@ -1,7 +1,7 @@
 #!/bin/bash
 # Copyright 1999-2004 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
-# $Header: /local/data/ulm/cvs/history/var/cvsroot/gentoo-src/portage/bin/Attic/emerge-webrsync,v 1.8.2.1 2004/11/02 14:56:57 jstubbs Exp $
+# $Header: /local/data/ulm/cvs/history/var/cvsroot/gentoo-src/portage/bin/Attic/emerge-webrsync,v 1.8.2.2 2004/12/17 22:25:13 carpaski Exp $
 # Author: Karl Trygve Kalleberg <karltk@gentoo.org>
 # Rewritten from the old, Perl-based emerge-webrsync script
 
@@ -9,7 +9,7 @@ GENTOO_MIRRORS="${GENTOO_MIRRORS} $(/usr/lib/portage/bin/portageq gentoo_mirrors
 PORTDIR="$(/usr/lib/portage/bin/portageq portdir)"
 FETCHCOMMAND="$(/usr/lib/portage/bin/portageq envvar FETCHCOMMAND)"
 USERLAND="$(/usr/lib/portage/bin/portageq envvar USERLAND)"
-DISTDIR="/var/tmp/emerge-webrsync"
+DISTDIR="$(/usr/lib/portage/bin/portageq envvar PORTAGE_TMPDIR)/emerge-webrsync"
 
 if [ ! -d $DISTDIR ] ; then
 	mkdir -p $DISTDIR
@@ -42,7 +42,11 @@ fi
 
 sync_local() {
 	echo Syncing local tree...
-	tar jxf $FILE
+	if !tar jxf $FILE; then
+		echo "Tar failed to extract the image. Please review the output."
+		echo "Executed command: tar jxf $FILE"
+		exit 1
+	fi
 	rm -f $FILE
 	# Make sure user and group file ownership is root
 	chown -R 0:0 portage
